# Generated by Django 4.1.3 on 2022-12-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_brand_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="price",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
