# Generated by Django 4.1.3 on 2022-12-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_order_remove_cart_address_remove_cart_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
